version: "3"
services:
  frontend:
    build: ml-kurkkumopo-frontend
    ports:
      - "3000:3000"
  backend:
    build: ml-kurkkumopo-backend
    ports:
      - "5000:5000"
    volumes:
      - ./volumes/model:/src/model
  training:
    build: ml-kurkkumopo-training
    volumes:
      - ./volumes/imgs:/src/imgs
      - ./volumes/data:/src/data
      - ./volumes/model:/src/model
